#pragma once

enum class FuncType;

enum class FuncType {
	_default                        = (-1), 
	register_patient                = 0,
	update_patient                  = 1,
	get_patient_data                = 2,
	generate_patient_id             = 3,
	get_patient_med_data            = 4,
	get_patient_tests               = 5,
	get_test_data                   = 6,
	push_test_data                  = 7,
	get_appointment_data            = 8,
	check_doctor_id                 = 9,
	get_appointment_patient_data    = 10,
	get_meeting_data                = 11,
	push_presc                      = 12,
	push_tests                      = 13,
	admit_patient                   = 14,
	appointment_done                = 15,
	get_patient_record              = 16,
	get_test_history                = 17,
	get_complete_test_data          = 18,
	get_appointment_history         = 19,
	get_presc_data                  = 20,
	get_patient_information         = 21,
	get_doctor_data                 = 22,
	get_admit_request               = 23,
	get_room_data                   = 24,
	get_room_patient_id             = 25,
	frontdesk_admit_patient         = 26,
	get_discharge_details           = 27,
	frontdesk_discharge_patient     = 28,
	get_admit_history               = 29,
	get_doctor_speciality           = 30,
	get_appointment_slots           = 31,
	confirm_appointment             = 32,
	add_appointment                 = 33,
	get_schedule_test               = 34,
	get_test_slots                  = 35,
	confirm_test                    = 36,
	add_test                        = 37,
	get_doctor_id                   = 38,
	add_doctor                      = 39,
	delete_doctor                   = 40,
	get_doctor_details              = 41,
	update_doctor                   = 42,
	view_doctor                     = 43,
	check_frontdesk_login           = 44,
	check_dataentry_login           = 45,
	check_doctor_login              = 46,
	check_admin_login               = 47
};